### ISSUE TITLE
Maximum sentences?

### ISSUE THREAD

**Issue by ghost** [willplatt/LearnTatoeba#2]
Hello! Hope you're doing fine :)
This program is awesome!
Wondering if it's possible to change the amount of new sentences per review?
Couldn't find it in the settings.
Thanks a bunch

**Comment by willplatt** [comment]
Hi! I'm well thanks; I hope you are too. I'm glad you like the software.

The current master branch has a number of features added after the v0.1.0 release, including the ability to change the session length in the account settings. I've attached a build here to save you the trouble of building it. Just bear in mind it's not a polished release and there might be some issues updating from it to future releases. (So you should copy your data before updating to any future release to avoid losing anything. If you have issues updating then you can ask here for help.) Enjoy!

I haven't touched this project in 2 years but I hope it's not too long before I get to work on it again, as it has lots of potential. It's just a matter priorities, motivation, and finding time.

[LearnTatoeba-0.1.0dev.zip](https://github.com/willplatt/LearnTatoeba/files/9558581/LearnTatoeba-0.1.0dev.zip)
